import pytest
from unittest.mock import patch, MagicMock
from app.engine.firms_client import fetch_firms_data, process_firms_csv

from fastapi.testclient import TestClient
from app.main import app
import os
import asyncpg

os.environ["DATABASE_URL"] = "postgresql://geoflare_user:geoflare_password@127.0.0.1:5433/geoflare"
os.environ["FIRMS_ENABLED"] = "true"

import random

def get_sample_csv():
    # use random acq_time to bypass deduplication when tests re-run against same DB
    h = random.randint(0, 23)
    m = random.randint(0, 59)
    acq_time = f"{h:02d}{m:02d}"
    return f"""latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
19.0,73.0,310.5,1.0,1.0,2026-08-27,{acq_time},N,VIIRS,n,2.0,290.0,15.5,D
-100.0,200.0,300.0,1.0,1.0,2026-08-27,{acq_time},N,VIIRS,n,2.0,290.0,15.5,D
"""

@pytest.mark.anyio
async def test_process_firms_csv_and_deduplication():
    # Use asyncpg directly to avoid TestClient sync context issues
    pool = await asyncpg.create_pool(os.environ["DATABASE_URL"])
    csv_data = get_sample_csv()
    try:
        # Process first time
        result = await process_firms_csv(csv_data, pool, "TEST_SOURCE")
        assert result["fetched"] == 2
        assert result["accepted"] == 1
        assert result["rejected"] == 1
        
        # Process second time (should be deduplicated)
        result2 = await process_firms_csv(csv_data, pool, "TEST_SOURCE")
        assert result2["fetched"] == 2
        assert result2["accepted"] == 0
        assert result2["rejected"] == 2
    finally:
        await pool.close()

from unittest.mock import patch, MagicMock, AsyncMock

@patch("app.engine.firms_client.httpx.AsyncClient")
@patch("app.api.v1.ingestion.FIRMS_ENABLED", True)
def test_trigger_firms_ingestion_endpoint(mock_client_class):
    mock_response = MagicMock()
    mock_response.text = get_sample_csv()
    mock_response.raise_for_status.return_value = None
    
    mock_client_instance = MagicMock()
    mock_client_instance.get = AsyncMock(return_value=mock_response)
    mock_client_instance.__aenter__.return_value = mock_client_instance
    mock_client_instance.__aexit__.return_value = None
    mock_client_class.return_value = mock_client_instance
    
    with TestClient(app) as client:
        response = client.post("/api/v1/ingestion/firms?source=MOCK_SOURCE")
        if response.status_code != 200:
            print("Error response:", response.json())
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "success"
        assert data["metrics"]["fetched"] == 2
        assert data["metrics"]["accepted"] == 1
        assert data["metrics"]["rejected"] == 1

@patch("app.engine.firms_client.httpx.AsyncClient")
@patch("app.api.v1.ingestion.FIRMS_ENABLED", True)
def test_firms_ingestion_empty_response(mock_client_class):
    mock_response = MagicMock()
    # Provide only headers, no data rows
    mock_response.text = "latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight\n"
    mock_response.raise_for_status.return_value = None
    
    mock_client_instance = MagicMock()
    mock_client_instance.get = AsyncMock(return_value=mock_response)
    mock_client_instance.__aenter__.return_value = mock_client_instance
    mock_client_instance.__aexit__.return_value = None
    mock_client_class.return_value = mock_client_instance
    
    with TestClient(app) as client:
        response = client.post("/api/v1/ingestion/firms?source=MOCK_EMPTY")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "success"
        assert data["metrics"]["fetched"] == 0
        assert data["metrics"]["accepted"] == 0

@patch("app.engine.firms_client.httpx.AsyncClient")
@patch("app.api.v1.ingestion.FIRMS_ENABLED", True)
def test_firms_ingestion_api_error(mock_client_class):
    import httpx
    
    mock_client_instance = MagicMock()
    # Simulate a network/API error
    mock_client_instance.get = AsyncMock(side_effect=httpx.RequestError("Network error", request=MagicMock()))
    mock_client_instance.__aenter__.return_value = mock_client_instance
    mock_client_instance.__aexit__.return_value = None
    mock_client_class.return_value = mock_client_instance
    
    with TestClient(app) as client:
        response = client.post("/api/v1/ingestion/firms?source=MOCK_ERROR")
        assert response.status_code == 500
        
        # Verify no fallback data was silently ingested by checking ingestion status or fires endpoint
        response_fires = client.get("/api/v1/fires")
        assert response_fires.status_code == 200
        data_fires = response_fires.json()
        # Ensure no synthetic records were generated by the error handler
        assert isinstance(data_fires["features"], list)

@pytest.mark.anyio
async def test_spatial_grouping():
    # Insert one observation, then insert a second one very close, and a third one far away.
    pool = await asyncpg.create_pool(os.environ["DATABASE_URL"])
    try:
        # Clear hotspots first to have a clean slate for this test
        async with pool.acquire() as conn:
            await conn.execute("DELETE FROM fire_observations")
            await conn.execute("DELETE FROM hotspots")
            
        csv_1 = "latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight\n19.000,73.000,310.5,1.0,1.0,2026-08-27,1000,N,VIIRS,n,2.0,290.0,15.5,D\n"
        # 0.005 degrees is approx 550m (within 1000m)
        csv_2 = "latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight\n19.004,73.000,310.5,1.0,1.0,2026-08-27,1005,N,VIIRS,n,2.0,290.0,15.5,D\n"
        # 10.0 degrees is ~1100km (well outside 1000m)
        csv_3 = "latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight\n29.000,73.000,310.5,1.0,1.0,2026-08-27,1010,N,VIIRS,n,2.0,290.0,15.5,D\n"
        
        await process_firms_csv(csv_1, pool, "TEST_SPATIAL")
        await process_firms_csv(csv_2, pool, "TEST_SPATIAL")
        await process_firms_csv(csv_3, pool, "TEST_SPATIAL")
        
        async with pool.acquire() as conn:
            hotspots = await conn.fetch("SELECT id, observation_count FROM hotspots")
            assert len(hotspots) == 2, f"Expected 2 hotspots, got {len(hotspots)}"
            
            counts = [h['observation_count'] for h in hotspots]
            assert 2 in counts, "Expected one hotspot to group 2 close observations"
            assert 1 in counts, "Expected the distant observation to form its own hotspot"
    finally:
        await pool.close()
